external-secrets:
  installCRDs: true

  serviceAccount:
    create: true
    name: "external-secrets"

  replicaCount: 2

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: external-secrets
          topologyKey: kubernetes.io/hostname

  webhook:
    certManager:
      enabled: false

  nodeSelector:
    team: "platform-engineering"
    workload: "critical"
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "platform-engineering"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 256Mi


  certController:
    nodeSelector:
      team: "platform-engineering"
      workload: "critical"
    tolerations:
      - key: "team"
        operator: "Equal"
        value: "platform-engineering"
        effect: "NoSchedule"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi

  webhook:
    nodeSelector:
      team: "platform-engineering"
      workload: "critical"
    tolerations:
      - key: "team"
        operator: "Equal"
        value: "platform-engineering"
        effect: "NoSchedule"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
