github_project        = "https://github.com/l0s3rc0d3/platform-engineering-demo"
github_gitops_project = "https://github.com/l0s3rc0d3/platform-engineering-gitops"
sdlc_env              = "demo"
aws_region            = "eu-west-1"
eks_name              = "demo"